Feature: Query unit tests

    Scenario Outline: Keywords are built into search terms
        Given a dictionary of keywords with the categories <method> <volume> <production> and <feedstock>
        When I build the search terms from the keywords
        Then the search terms should be <expected_terms>

        Examples:
            | method                                   | volume                     | production                                            | feedstock                                   | expected_terms                                                                                                                                                                                                                                                 |
            | biomanufacturing,bioreactor,fermentation | ton,tons,tonnes,metric_ton | production_capacity,annual_production,annual_capacity | corn,sugar,sugarcane,biomass,starch,glucose | ("biomanufacturing" OR "bioreactor" OR "fermentation"), ("ton" OR "tons" OR "tonnes" OR "metric ton"), ("production capacity" OR "annual production" OR "annual capacity"), ("corn" OR "sugar" OR "sugarcane" OR "biomass" OR "starch" OR "glucose") |
            | biomanufacturing,bioreactor,fermentation | ton,tons,tonnes,metric_ton | production_capacity,annual_production,annual_capacity | empty                                       | ("biomanufacturing" OR "bioreactor" OR "fermentation"), ("ton" OR "tons" OR "tonnes" OR "metric ton"), ("production capacity" OR "annual production" OR "annual capacity")                                                                             |
            | biomanufacturing,bioreactor,fermentation | ton,tons,tonnes,metric_ton | empty                                                 | empty                                       | ("biomanufacturing" OR "bioreactor" OR "fermentation"), ("ton" OR "tons" OR "tonnes" OR "metric ton")                                                                                                                                                    |
            | empty                                    | empty                      | empty                                                 | empty                                       | empty                                                                                                                                                                                                                                                             |